version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.2
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          DATABASE_URL: postgres://postgres:@localhost:5432/billing_engine_test?encoding=utf8&pool=5
          RAILS_ENV: test
      - image: circleci/postgres:latest
        environment:
          POSTGRES_DB: billing_engine_test

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - bundle-v1-{{ checksum "Gemfile.lock" }}
            - bundle-v1-
      - run:
          name: Installing gems
          command: bin/bundle check || bin/bundle install
      - save_cache:
          key: bundle-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle

      - run:
          name: Waiting for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bin/rails db:schema:load --trace

      - run:
          name: Rubocop
          command: |
            bin/bundle exec rubocop --config ./.rubocop.yml
      - run:
          name: Minitest
          command: |
            bin/bundle exec rake test \
              $(circleci tests glob "test/**/*_test.rb" \
              | circleci tests split --split-by=timings --timings-type=classname)

      - store_test_results:
          path: /tmp/test-results
